name: Synch to hugging face hub
on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: write
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Define remote
        env:
          HF_TOKEN: ${{ secrets.HF }}
        run: git remote set-url origin https://ramse86:$HF_TOKEN@huggingface.co/spaces/ramse86/demo
      - name: Add remote
        env:
          HF_TOKEN: ${{ secrets.HF }}
        run: git remote add space https://ramse86:$HF_TOKEN@huggingface.co/spaces/ramse86/demo
      - name: Push to hub
        env:
          HF_TOKEN_PUSH: ${{ secrets.HF }}
        run: git push --force https://ramse86:$HF_TOKEN_PUSH@huggingface.co/spaces/ramse86/demo main
