name: Synch to hugging face hub
on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: write
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://ramse86:$HF@huggingface.co/spaces/ramse86/demo
      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://ramse86:$HF@huggingface.co/spaces/ramse86/demo main
